- name: Install Docker engine
  hosts: "*"
  become: true
  tasks:
  - name: install dependencies
    apt:
      name: 
       - ca-certificates 
       - lsb-release
       - apt-transport-https 
       - ca-certificates 
       - software-properties-common
       - curl 
       - gnupg 
       - lsb-release
      state: present
      update_cache: true
    become: true

  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: add docker repository to apt
    apt_repository:
      filename: docker 
      repo: \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \ 
      #deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
      state: present

  - name: install docker engine
    apt:
      name: 
        - docker.ce 
        - docker-ce-cli 
        - containerd.io
        - docker compose
        - docker-compose-plugin
        - docker-buildx-plugin
      state: present
      update_cache: true
    become: true

  - name: test docker
    command: docker info
    become: true
