---
- name: Install Python 3 if not present
- hosts:  "*"
  become: true
  tasks:
    - name: Check if Python 3 is installed
      command: python3 --version
      register: python3_check
      ignore_errors: true

    - name: Install Python 3
      apt:
        name: python3
        state: present
      when: python3_check.rc != 0
